language: python
python:
    - "3.2"
    - "3.3"
    - "3.4"
    - "3.5"
    - "nightly"
install:
    - pip install python-coveralls pytest-cov
    - pip install .
script: 
    - py.test tests --cov debugtools
after_success:
    - coveralls
